import { ANCHOR_SEPARATOR, POOL } from "./pool.js";

export const READ_ANCHORED_DESCRIPTION = `Read a file with one anchor prefix per line in the format "<anchor>${ANCHOR_SEPARATOR}<content>". When parsing a returned line, split on the first ${ANCHOR_SEPARATOR} character; later ${ANCHOR_SEPARATOR} characters belong to file content. Anchors are opaque IDs drawn from a session-scoped pool of ${POOL.length} single-BPE-token capitalized English words; once the pool is exhausted, the allocator falls back to multi-word concatenations (e.g. "MorelloMagnificent"), which are no longer single-token but remain unique. Anchors are stable across edits unless the line itself changes (Myers-diff reconciler reassigns only changed lines). Use the anchor in subsequent edit_anchored calls instead of repeating line content. Returns empty content if offset is at or beyond the file's line count.`;

export const EDIT_ANCHORED_DESCRIPTION = `Edit a file by anchor reference. Modes: "replace" (overwrite lines from start_anchor through end_anchor inclusive; end_anchor defaults to start_anchor for single-line replace), "insert_before" (insert new_content as new lines above start_anchor), "insert_after" (insert below start_anchor). To delete one or more lines, use mode=replace with empty new_content (set end_anchor for multi-line deletion). Rejects with ANCHOR_NOT_FOUND if start_anchor or end_anchor is missing in the current map. CRLF input is normalized to LF on write. The reply shows the affected range with refreshed anchors so you can chain follow-up edits without re-reading. For bulk same-string substitution within a file, prefer a CLI tool (sd 'pattern' 'replacement' file, rg --replace 'replacement' 'pattern' file, sg run --rewrite ...) or the host's replace-all primitive; anchored edits pay off for chained surgical edits where line stability matters.`;

export const WRITE_TO_FILE_DESCRIPTION =
  "Write full content to a file (creates the file if missing, overwrites if it exists). Prefer edit_anchored for surgical changes; use write_to_file for new files or full rewrites. Content is written as supplied; subsequent reads tolerate CRLF. Returns the rebuilt anchor map (Myers-diffed against any cached state) so unchanged lines keep their anchors without a follow-up read_anchored call.";

export const EDIT_MODE_DESCRIPTION =
  "replace: overwrite lines from start_anchor through end_anchor inclusive, or delete the range by passing empty new_content; insert_before: insert new_content above start_anchor's line; insert_after: insert below start_anchor's line.";
